import { Args, Flags } from '@oclif/core';
import { BaseCommand } from '../base.js';
import {
  listEvents,
  listRuns,
  listSteps,
  printStream,
  showRun,
  showStep,
} from '../lib/inspect/output.js';
import { getWorld } from '../lib/inspect/world.js';

export default class Inspect extends BaseCommand {
  static description = 'Inspect runs, steps, streams, or events';

  static aliases = ['i'];

  static examples = ['$ workflow inspect runs'];

  static args = {
    resource: Args.string({
      description: 'what to inspect: run(s) | step(s) | stream(s) | event(s)',
      required: true,
      options: [
        'r',
        'run',
        'runs',
        's',
        'step',
        'steps',
        'e',
        'event',
        'events',
        'st',
        'stream',
        'streams',
      ],
    }),
    id: Args.string({
      description:
        'ID of the run (for runs) or run-id (for steps/streams/events)',
      required: false,
    }),
    subId: Args.string({
      description:
        'optional step-id or stream-id when inspecting a specific item',
      required: false,
      dependsOn: ['id'],
    }),
  } as const;

  static flags = {
    target: Flags.string({
      description: 'target to inspect (vercel or embedded)',
      required: false,
      options: ['vercel', 'embedded'],
      char: 't',
      default: 'embedded',
    }),
    env: Flags.string({
      description: 'environment to inspect (production or preview)',
      required: false,
      options: ['production', 'preview'],
      default: 'production',
      char: 'e',
      dependsOn: ['target'],
    }),
    authToken: Flags.string({
      description:
        'Authentication token for the target backend. If not provided and the backend target is vercel, will fall back to the token generated by `wf login`.',
      required: false,
      char: 'a',
      dependsOn: ['target'],
    }),
  } as const;

  public async run(): Promise<void> {
    const { args, flags } = await this.parse(Inspect);

    if (flags.env !== 'production') {
      throw new Error('Preview environments are not supported yet');
    }

    const world = await getWorld({
      world: flags.target as 'embedded' | 'vercel',
      env: flags.env as 'production' | 'preview',
      authToken: flags.authToken,
    });

    const normalizeTarget = (
      value?: string
    ): 'run' | 'step' | 'stream' | 'event' | undefined => {
      if (!value) return undefined;
      const v = value.toLowerCase();
      if (v.startsWith('run')) return 'run';
      if (v.startsWith('step')) return 'step';
      if (v.startsWith('stream')) return 'stream';
      if (v.startsWith('event')) return 'event';
      return undefined;
    };

    const resource = normalizeTarget(args.resource);
    if (!resource) {
      this.logInfo(
        'You must specify what to inspect: runs(s), step(s), stream(s), or event(s).\n'
      );
      this.logInfo('Examples:');
      for (const ex of Inspect.examples) this.logInfo(`  ${ex}`);
      this.logInfo('');
      this.logInfo('Aliases:');
      this.logInfo("- Command: 'inspect' can be shortened to 'i'");
      this.logInfo(
        '- Targets: plural forms are accepted: runs, steps, streams'
      );
      return;
    }

    const id = args.id;
    const subId = args.subId;

    this.logInfo('');

    if (resource === 'run') {
      if (id) {
        await showRun(world, id);
      } else {
        await listRuns(world);
      }
      return;
    }

    if (resource === 'step') {
      if (!id) {
        this.logError(
          'Missing required argument: run-id. Usage: inspect steps <run-id> [<step-id>]'
        );
        return;
      }
      if (subId) {
        await showStep(world, id, subId);
      } else {
        await listSteps(world, id);
      }
      return;
    }

    if (resource === 'stream') {
      if (!id) {
        this.logError(
          'Missing required argument: run-id. Usage: inspect streams <run-id> [<stream-id>]'
        );
        return;
      }
      await printStream(world, id);
      return;
    }

    if (resource === 'event') {
      if (!id) {
        this.logError(
          'Missing required argument: run-id. Usage: inspect events <run-id>'
        );
        return;
      }
      if (subId) {
        this.logError(
          'Sub-ID is not supported for events. Usage: inspect events <run-id>'
        );
        return;
      }
      await listEvents(world, id);
      return;
    }
  }
}
