import { Args, Flags } from '@oclif/core';
import chalk from 'chalk';
import { BaseCommand } from '../base.js';
import {
  LOGGING_CONFIG,
  setJsonMode,
  setVerboseMode,
  showBox,
} from '../lib/config/log.js';
import {
  listEvents,
  listRuns,
  listSteps,
  listStreams,
  showRun,
  showStep,
  showStream,
} from '../lib/inspect/output.js';
import { getWorld } from '../lib/inspect/world.js';

export default class Inspect extends BaseCommand {
  static description = 'Inspect runs, steps, streams, or events';

  static aliases = ['i'];

  static examples = [
    '$ workflow inspect runs',
    '$ wf i runs',
    '$ wf i events --step=step_01K5WAJZ8W367CV2RFKDSDNWB8',
  ];

  async catch(error: any) {
    if (LOGGING_CONFIG.VERBOSE_MODE) {
      console.error(error);
    }
    throw error;
  }

  static args = {
    resource: Args.string({
      description: 'what to inspect: run(s) | step(s) | stream(s) | event(s)',
      required: true,
      options: [
        'r',
        'run',
        'runs',
        's',
        'step',
        'steps',
        'e',
        'event',
        'events',
        'st',
        'stream',
        'streams',
      ],
    }),
    id: Args.string({
      description: 'ID of the resource if inspecting a specific item',
      required: false,
    }),
  } as const;

  static flags = {
    runId: Flags.string({
      description: 'run ID to filter by',
      required: false,
      char: 'r',
      aliases: ['run'],
      helpGroup: 'Filtering',
      helpLabel: '-r, --runId',
      helpValue: 'RUN_ID',
    }),
    stepId: Flags.string({
      description: 'step ID to filter by',
      required: false,
      char: 's',
      aliases: ['step'],
      helpGroup: 'Filtering',
      helpLabel: '-s, --stepId',
      helpValue: 'STEP_ID',
    }),
    verbose: Flags.boolean({
      description: 'Verbose output',
      required: false,
      char: 'v',
      helpGroup: 'Output',
      helpLabel: '-v, --verbose',
      env: 'DEBUG',
      default: false,
    }),
    json: Flags.boolean({
      description: 'output JSON instead of human-readable tables/streams',
      required: false,
      char: 'j',
      default: false,
      helpGroup: 'Output',
      helpLabel: '-j, --json',
    }),
    cursor: Flags.string({
      description: 'pagination cursor for list commands',
      required: false,
      helpGroup: 'Filtering',
      helpLabel: '--cursor',
      helpValue: 'CURSOR',
    }),
    backend: Flags.string({
      description: 'backend to inspect',
      required: false,
      options: ['vercel', 'embedded', 'custom'],
      char: 'b',
      default: 'embedded',
      env: 'WORKFLOW_BACKEND',
      helpGroup: 'Target',
      helpLabel: '-b, --backend',
      helpValue: ['vercel', 'embedded', 'custom'],
      defaultHelp: 'embedded',
    }),
    authToken: Flags.string({
      description:
        'Authentication token to be passed to the backend. If not provided and the backend is vercel, will fall back to the token generated by `vc login`.',
      required: false,
      char: 'a',
      dependsOn: ['backend'],
      env: 'WORKFLOW_AUTH_TOKEN',
      helpGroup: 'Target',
      helpLabel: '-a, --authToken',
      helpValue: 'TOKEN',
    }),
    project: Flags.string({
      description:
        'If backend is vercel, the vercel project to authenticate against',
      required: false,
      dependsOn: ['backend'],
      env: 'VERCEL_PROJECT',
      helpGroup: 'Target',
      helpLabel: '--project',
      helpValue: 'PROJECT',
    }),
    team: Flags.string({
      description:
        'If backend is vercel, the vercel team to authenticate against',
      required: false,
      dependsOn: ['backend'],
      env: 'VERCEL_TEAM',
      helpGroup: 'Target',
      helpLabel: '--team',
      helpValue: 'TEAM',
    }),
    env: Flags.string({
      description: 'If backend is vercel, the vercel environment to use',
      required: false,
      options: ['production', 'preview'],
      default: 'production',
      char: 'e',
      dependsOn: ['backend'],
      env: 'VERCEL_ENV',
      helpGroup: 'Target',
      helpLabel: '-e, --env',
      helpValue: ['production', 'preview'],
      defaultHelp: 'production',
    }),
  } as const;

  public async run(): Promise<void> {
    const { args, flags } = await this.parse(Inspect);
    setJsonMode(Boolean(flags.json));
    setVerboseMode(Boolean(flags.verbose));

    const version = await this.config.version;
    showBox(
      'green',
      `        Workflow CLI v${version}        `,
      'Docs at https://workflow-docs.vercel.sh/',
      chalk.yellow('This is an alpha release - commands might change')
    );

    const world = await getWorld({
      world: flags.backend as 'embedded' | 'vercel',
      env: flags.env as 'production' | 'preview',
      authToken: flags.authToken,
      projectId: flags.project,
      teamId: flags.team,
    });
    process.env.DEBUG = flags.verbose ? '1' : '0';

    const resource = normalizeResource(args.resource);
    if (!resource) {
      this.logError(
        `Unknown resource "${args.resource}": must be one of: run(s), step(s), stream(s), event(s)`
      );
      return;
    }

    const id = args.id;

    if (resource === 'run') {
      if (id) {
        return await showRun(world, id, flags);
      }
      return await listRuns(world, flags);
    }

    if (resource === 'step') {
      if (id) {
        return await showStep(world, id, flags);
      }
      return await listSteps(world, flags);
    }

    if (resource === 'stream') {
      if (id) {
        return await showStream(world, id, flags);
      }
      return await listStreams(world, flags);
    }

    if (resource === 'event') {
      if (id) {
        this.logError(
          'Event-ID is not supported for events. Filter by run-id or step-id instead. Usage: `wf i events --runId=<id>`'
        );
        return;
      }
      return await listEvents(world, flags);
    }

    this.logError(
      `Unknown resource: ${resource}. Usage: ${Inspect.examples.join('\n')}`
    );
  }
}

function normalizeResource(
  value?: string
): 'run' | 'step' | 'stream' | 'event' | undefined {
  if (!value) return undefined;
  const v = value.toLowerCase();
  if (v.startsWith('r')) return 'run';
  if (v.startsWith('e')) return 'event';
  if (v.startsWith('str')) return 'stream';
  if (v.startsWith('s')) return 'step';
  return undefined;
}
