import { Args, Flags } from '@oclif/core';
import { BaseCommand } from '../base.js';
import {
  LOGGING_CONFIG,
  logWarn,
  setJsonMode,
  setVerboseMode,
} from '../lib/config/log.js';
import {
  listEvents,
  listRuns,
  listSteps,
  listStreams,
  showRun,
  showStep,
  showStream,
} from '../lib/inspect/output.js';
import { getWorld } from '../lib/inspect/world.js';

export default class Inspect extends BaseCommand {
  static description = 'Inspect runs, steps, streams, or events';

  static aliases = ['i'];

  static examples = [
    '$ workflow inspect runs',
    '$ wf i runs',
    '$ wf i events --step=step_01K5WAJZ8W367CV2RFKDSDNWB8',
  ];

  async catch(error: any) {
    if (LOGGING_CONFIG.VERBOSE_MODE) {
      console.error(error);
    }
    throw error;
  }

  static args = {
    resource: Args.string({
      description: 'what to inspect: run(s) | step(s) | stream(s) | event(s)',
      required: true,
      options: [
        'r',
        'run',
        'runs',
        's',
        'step',
        'steps',
        'e',
        'event',
        'events',
        'st',
        'stream',
        'streams',
      ],
    }),
    id: Args.string({
      description: 'ID of the resource if inspecting a specific item',
      required: false,
    }),
  } as const;

  static flags = {
    runId: Flags.string({
      description: 'run ID to filter by',
      required: false,
      char: 'r',
      aliases: ['run'],
      helpGroup: 'Filtering',
      helpLabel: '-r, --runId',
      helpValue: 'RUN_ID',
    }),
    stepId: Flags.string({
      description: 'step ID to filter by',
      required: false,
      char: 's',
      aliases: ['step'],
      helpGroup: 'Filtering',
      helpLabel: '-s, --stepId',
      helpValue: 'STEP_ID',
    }),
    verbose: Flags.boolean({
      description: 'Verbose output',
      required: false,
      char: 'v',
      helpGroup: 'Output',
      helpLabel: '-v, --verbose',
      env: 'DEBUG',
      default: false,
    }),
    json: Flags.boolean({
      description: 'output JSON instead of human-readable tables/streams',
      required: false,
      char: 'j',
      default: false,
      helpGroup: 'Output',
      helpLabel: '-j, --json',
    }),
    backend: Flags.string({
      description: 'backend to inspect',
      required: false,
      options: ['vercel', 'embedded', 'custom'],
      char: 'b',
      default: 'embedded',
      env: 'WORKFLOW_BACKEND',
      helpGroup: 'Target',
      helpLabel: '-b, --backend',
      helpValue: ['vercel', 'embedded', 'custom'],
      defaultHelp: 'embedded',
    }),
    env: Flags.string({
      description: 'environment to inspect',
      required: false,
      options: ['production', 'preview'],
      default: 'production',
      char: 'e',
      dependsOn: ['backend'],
      env: 'WORKFLOW_ENV',
      helpGroup: 'Target',
      helpLabel: '-e, --env',
      helpValue: ['production', 'preview'],
      defaultHelp: 'production',
    }),
    authToken: Flags.string({
      description:
        'Authentication token to be passed to the backend. If not provided and the backend is vercel, will fall back to the token generated by `vc login`.',
      required: false,
      char: 'a',
      dependsOn: ['backend'],
      env: 'WORKFLOW_AUTH_TOKEN',
      helpGroup: 'Target',
      helpLabel: '-a, --authToken',
      helpValue: 'TOKEN',
    }),
    project: Flags.string({
      description:
        'If backend is vercel, the vercel project to authenticate against',
      required: false,
      dependsOn: ['backend'],
      env: 'VERCEL_PROJECT',
      helpGroup: 'Target',
      helpLabel: '--project',
      helpValue: 'PROJECT',
    }),
    team: Flags.string({
      description:
        'If backend is vercel, the vercel team to authenticate against',
      required: false,
      dependsOn: ['backend'],
      env: 'VERCEL_TEAM',
      helpGroup: 'Target',
      helpLabel: '--team',
      helpValue: 'TEAM',
    }),
    hostUrl: Flags.string({
      description: 'The host URL that the target backend is running on',
      required: false,
      dependsOn: ['backend'],
      env: 'WORKFLOW_HOST_URL',
      char: 'h',
      helpGroup: 'Target',
      helpLabel: '-h, --hostUrl',
      helpValue: 'URL',
    }),
  } as const;

  public async run(): Promise<void> {
    const { args, flags } = await this.parse(Inspect);
    setJsonMode(Boolean(flags.json));
    setVerboseMode(Boolean(flags.verbose));

    logWarn('===================================================');
    logWarn('Workflow CLI is experimental, commands might change');
    logWarn('===================================================');

    if (flags.env !== 'production') {
      throw new Error('Preview environments are not supported yet');
    }

    const world = await getWorld({
      world: flags.backend as 'embedded' | 'vercel',
      env: flags.env as 'production' | 'preview',
      authToken: flags.authToken,
      projectId: flags.project,
      teamId: flags.team,
      hostUrl: flags.hostUrl,
    });

    const normalizeResource = (
      value?: string
    ): 'run' | 'step' | 'stream' | 'event' | undefined => {
      if (!value) return undefined;
      const v = value.toLowerCase();
      if (v.startsWith('r')) return 'run';
      if (v.startsWith('e')) return 'event';
      if (v.startsWith('str')) return 'stream';
      if (v.startsWith('s')) return 'step';
      return undefined;
    };

    const resource = normalizeResource(args.resource);
    if (!resource) {
      this.logInfo(
        'You must specify what to inspect: runs(s), step(s), stream(s), or event(s).\n'
      );
      this.logInfo('Examples:');
      for (const ex of Inspect.examples) this.logInfo(`  ${ex}`);
      this.logInfo('');
      this.logInfo('Aliases:');
      this.logInfo("- Command: 'inspect' can be shortened to 'i'");
      this.logInfo(
        '- Resources: plural forms are accepted: runs, steps, streams'
      );
      return;
    }

    const id = args.id;

    if (resource === 'run') {
      if (id) {
        await showRun(world, id, flags);
      } else {
        await listRuns(world, flags);
      }
    } else if (resource === 'step') {
      if (id) {
        await showStep(world, id, flags);
      } else {
        await listSteps(world, flags);
      }
    } else if (resource === 'stream') {
      if (id) {
        await showStream(world, id, flags);
      } else {
        await listStreams(world, flags);
      }
    } else if (resource === 'event') {
      if (id) {
        this.logError(
          'Event-ID is not supported for events. Filter by run-id or step-id instead. Usage: `wf i events --runId=<id>`'
        );
        return;
      }
      await listEvents(world, flags);
    } else {
      this.logError(
        `Unknown resource: ${resource}. Usage: ${Inspect.examples.join('\n')}`
      );
      return;
    }
  }
}
