// NOTE:
// This file would be automatically generated by dev tooling,
// based on the steps defined using the file system convention
// and/or parsed out from the "use step" directives.
import { useStep } from './step';

export const add = useStep<[number, number], number>('add');
