// NOTE: this would be generated by the Workflow CLI
import { vercelAPIWebhooksEntrypoint } from '@vercel/workflow-core/runtime';

export const GET = vercelAPIWebhooksEntrypoint;
export const POST = vercelAPIWebhooksEntrypoint;
export const PUT = vercelAPIWebhooksEntrypoint;
export const DELETE = vercelAPIWebhooksEntrypoint;
export const PATCH = vercelAPIWebhooksEntrypoint;
export const OPTIONS = vercelAPIWebhooksEntrypoint;
export const HEAD = vercelAPIWebhooksEntrypoint;
