name: Tests

on:
  push:
    branches:
      - main
    tags:
      - '!*'
  pull_request:

jobs:
  unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.14.0

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Unit Tests
        run: pnpm test

  e2e:
    name: E2E Tests (${{ matrix.app.name }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        app:
          - name: "example-app"
            project-id: "prj_xWq20Dd860HHAfzMjK2Mb6TPVxMa"
          - name: "nextjs-app"
            project-id: "prj_yjkM7UdHliv8bfxZ1sMJQf1pMpdi"
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.14.0

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Waiting for the Vercel deployment
        id: waitForDeployment
        uses: ./.github/actions/wait-for-vercel-project
        with:
          team-id: 'team_nO2mCG4W8IxPIeKoSsqwAxxB'
          project-id: ${{ matrix.app.project-id }}
          vercel-token: ${{ secrets.VERCEL_LABS_TOKEN }}
          timeout: 1000
          check-interval: 15
          environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'preview' }}

      - name: Run E2E Tests
        run: pnpm run test:e2e
        env:
          DEPLOYMENT_URL: ${{ steps.waitForDeployment.outputs.deployment-url }}
