name: Tests

on:
  push:
    branches:
      - main
    tags:
      - '!*'
  pull_request:

jobs:
  unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.14.4

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Unit Tests
        run: pnpm test

  e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.14.4

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Waiting for the Vercel deployment
        uses: patrickedqvist/wait-for-vercel-preview@v1.3.2
        id: waitForDeployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 60

      - name: Run E2E Tests
        run: pnpm run test:e2e
        env:
          DEPLOYMENT_URL: ${{ steps.waitForDeployment.outputs.url }}
